@JwtAuthDemo_HostAddress = http://localhost:5203/api

### Register a new user
POST {{JwtAuthDemo_HostAddress}}/auth/register
Content-Type: application/json
{
  "UserName": "tri4",
  "Email": "tri4@gmail.com",
  "Password": "tri4"
}

### Login with the new user
# @name login
POST {{JwtAuthDemo_HostAddress}}/auth/login
Content-Type: application/json
{
  "email": "tri6@gmail.com",
  "password": "tri666"
}

### Get the result from the token control

GET {{JwtAuthDemo_HostAddress}}/user/me
Authorization: Bearer {{login.response.body.$.token}}
Accept: application/json

### Send forgot-password link email
POST {{JwtAuthDemo_HostAddress}}/auth/forgot-password
Content-Type: application/json
{
  "email": "selimballi13@gmail.com"
}
